image: node:18.20.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - yarn.lock
      prefix: yarn
    paths:
      - node_modules/
      - .yarn/cache/
  script:
    - yarn
    - yarn build
    - cp -a dist/. public/
    - echo '/* /index.html 200' > public/_redirects
  artifacts:
    paths:
      - public
